### ISSUE TITLE
Extra License

### ISSUE THREAD

**Issue by talend-glorieux** [isaacs/block-stream#11]
Why is there an extra license file named LICENCE on the repository and npm package ?

**Comment by isaacs** [comment]
The only reason that's there is for the strict.dtd example file, will remove it.  It's weird.

**Comment by isaacs** [comment]
oh, wait, wrong repo.  hah.

**Comment by isaacs** [comment]
Thanks, fixed.

**Comment by isaacs** [comment]
That being said, if you want to use this module under the terms of the BSD-3-Clause rather than ISC, I 100% have no problem with that.  They're functionally equivalent from my point of view.  Take your pick :)
